# Generated by Django 5.1 on 2024-11-16 14:17

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+0112989425', max_length=30, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='say something about yourself', verbose_name='About me')),
                ('facebook_url', models.URLField(default='www.facebook.com', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(default='www.instagram.com', verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(default='www.twitter.com', verbose_name='Twitter URL')),
                ('threads_url', models.URLField(default='www.threads.com', verbose_name='Threads URL')),
                ('license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Real Estate license')),
                ('profile_photo', models.ImageField(default='/profile_default.jpg', upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Nairobi', max_length=180, verbose_name='City')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are you looking to Buy a Property?', verbose_name='Buyer')),
                ('is_seller', models.BooleanField(default=False, help_text='Are you looking to sell a property?', verbose_name='Seller')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
