# Generated by Django 5.1 on 2024-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='140', max_length=100, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address',
            field=models.CharField(default='Aventh Avenue', max_length=150, verbose_name='Street Address'),
        ),
    ]
