# Generated by Django 5.1 on 2024-11-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model',
            field=models.CharField(default='', max_length=250, verbose_name='Model'),
        ),
    ]
