# Generated by Django 5.1 on 2024-11-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plot_area',
        ),
    ]
